### ISSUE TITLE
Add support for SonarQube 7.4+

### ISSUE THREAD

**Issue by fsantiag** [fsantiag/sonar-clojure#19]
Starting from SonarQube version 7.4, after sonnar-scanner analysis, the project overview reports _This project is empty_ which is not the correct behavior. We might need to update the sonar-plugin-api dependency.

**Comment by hjhamala** [comment]
I wrote this also on pull request thread:

This is most likely cause because the plugin does not add loc-statistics to the project.

If you add any other file to the project which can be analyzed by SonarQube (like xml-file) and also make sure that the file is in projects source then project is showed.

I have a almost finished syntax highlighter and tokenizer which calculates ncloc etc and when that sensor is running the project overview does show properly.

**Comment by caipivara** [comment]
I see `This project is empty.` everytime I run it on 7.4

**Comment by fsantiag** [comment]
@caipivara yes, this is expected so far. You can refer to the [README](https://github.com/fsantiag/sonar-clojure#compatibility) file for further information.

**Comment by caipivara** [comment]
@fsantiag it mentions a `resources folder` what does it mean?

> If using later versions than SonarQube 7.1 then the project overview might be empty. This can be fixed by adding a xml file or other SonarQube analyzable file to scanned files for example to resources folder. Remember to check that the folder is also in sonar.sources property.

**Comment by fsantiag** [comment]
> @fsantiag it mentions a `resources folder` what does it mean?
> 
> > If using later versions than SonarQube 7.1 then the project overview might be empty. This can be fixed by adding a xml file or other SonarQube analyzable file to scanned files for example to resources folder. Remember to check that the folder is also in sonar.sources property.

I think `resources folder` actually mean `sources folder`. I will update that.
It means that if you include any file in the sources directory (normally specified by the property `sonar.sources` in the _sonar-project.properties_) the scan will work.
Keep in mind this might not be the case for every project. We observed this behaviour in a few projects we tested.

**Comment by MatiasNielsen** [comment]
anything new on this?

Using docker to get sonar scanner to scan a clojure project, and it says analysis successfull but the "project is empty" in sonarqube 7.7

**Comment by MatiasNielsen** [comment]
I'd like to know how to solve this issue. im getting all sorts of "is not a task"
03:23:34.010 WARN: Stderr: 'eastwood' is not a task. See 'lein help'.
03:23:35.232 WARN: Stderr: 'kibit' is not a task. See 'lein help'.
03:23:36.383 WARN: Stderr: 'ancient' is not a task. See 'lein help'.

**Comment by fsantiag** [comment]
Hi @MatiasNielsen, have you included the plugins in your `project.clj` file? That error suggests that they are missing.

**Comment by MatiasNielsen** [comment]
Hi,

when i run the lein kibit (as an example) in the folder where the project.clj exists, it actually scans the code and comes with suggestions, but im trying to run this scanner in a docker from jenkins. 
1. Get Code (jenkins handles this part as of right now)
2. Install Lein
3. Run sonar scan 
4. The plugin says "Task bla bla is not found".

Im getting the same error when im running the lein kibit from other folders BUT the one above. When i run it from the same folder as project.clj is in, it works fine (on my local machine).. So im not sure if its trying in the wrong directory in the docker image, and thats why it says task not found..

`Matiass-MacBook-Pro:UFST matias$ cd Clojurehelloworld/
Matiass-MacBook-Pro:Clojurehelloworld matias$ clear
Matiass-MacBook-Pro:Clojurehelloworld matias$ lein help
Leiningen is a tool for working with Clojure projects.

Several tasks are available:
change              Rewrite project.clj by applying a function.
check               Check syntax and warn on reflection.
classpath           Print the classpath of the current project.
clean               Remove all files from project's target-path.
compile             Compile Clojure source into .class files.
deploy              Build and deploy jar to remote repository.
deps                Download all dependencies.
do                  Higher-order task to perform other tasks in succession.
help                Display a list of tasks or help for a given task.
install             Install the current project to the local repository.
jar                 Package up all the project's files into a jar file.
javac               Compile Java source files.
new                 Generate project scaffolding based on a template.
plugin              DEPRECATED. Please use the :user profile instead.
pom                 Write a pom.xml file to disk for Maven interoperability.
release             Perform :release-tasks.
repl                Start a repl session either with the current project or standalone.
retest              Run only the test namespaces which failed last time around.
run                 Run a -main function with optional command-line arguments.
search              Search Central and Clojars for published artifacts.
show-profiles       List all available profiles or display one if given an argument.
test                Run the project's tests.
trampoline          Run a task without nesting the project's JVM inside Leiningen's.
uberjar             Package up the project files and dependencies into a jar file.
update-in           Perform arbitrary transformations on your project map.
upgrade             Upgrade Leiningen to specified version or latest stable.
vcs                 Interact with the version control system.
version             Print version for Leiningen and the current JVM.
with-profile        Apply the given task with the profile(s) specified.

Run `lein help $TASK` for details.

Global Options:
  -o             Run a task offline.
  -U             Run a task after forcing update of snapshots.
  -h, --help     Print this help or help for a specific task.
  -v, --version  Print Leiningen's version.

These aliases are available:
downgrade, expands to upgrade

See also: readme, faq, tutorial, news, sample, profiles, deploying, gpg,
mixed-source, templates, and copying.
Matiass-MacBook-Pro:Clojurehelloworld matias$ cd hello-world/
Matiass-MacBook-Pro:hello-world matias$ lein help
Leiningen is a tool for working with Clojure projects.

Several tasks are available:
ancient             Check your projects and profiles for outdated dependencies/plugins.
auto                Executes the given task every time a file in the project is modified.
change              Rewrite project.clj by applying a function.
check               Check syntax and warn on reflection.
classpath           Print the classpath of the current project.
clean               Remove all files from project's target-path.
cloverage           Run code coverage on the project.
compile             Compile Clojure source into .class files.
deploy              Build and deploy jar to remote repository.
deps                Download all dependencies.
do                  Higher-order task to perform other tasks in succession.
leiningen.eastwood  Problem loading: Wrong number of args (0) passed to: leiningen.eastwood/help
help                Display a list of tasks or help for a given task.
install             Install the current project to the local repository.
jar                 Package up all the project's files into a jar file.
javac               Compile Java source files.
kibit
new                 Generate project scaffolding based on a template.
nvd
plugin              DEPRECATED. Please use the :user profile instead.
pom                 Write a pom.xml file to disk for Maven interoperability.
release             Perform :release-tasks.
repl                Start a repl session either with the current project or standalone.
retest              Run only the test namespaces which failed last time around.
run                 Run a -main function with optional command-line arguments.
search              Search Central and Clojars for published artifacts.
show-profiles       List all available profiles or display one if given an argument.
test                Run the project's tests.
trampoline          Run a task without nesting the project's JVM inside Leiningen's.
uberjar             Package up the project files and dependencies into a jar file.
update-in           Perform arbitrary transformations on your project map.
upgrade             Upgrade Leiningen to specified version or latest stable.
vcs                 Interact with the version control system.
version             Print version for Leiningen and the current JVM.
with-profile        Apply the given task with the profile(s) specified.

Run `lein help $TASK` for details.

Global Options:
  -o             Run a task offline.
  -U             Run a task after forcing update of snapshots.
  -h, --help     Print this help or help for a specific task.
  -v, --version  Print Leiningen's version.

These aliases are available:
downgrade, expands to upgrade

See also: readme, faq, tutorial, news, sample, profiles, deploying, gpg,
mixed-source, templates, and copying.`

**Comment by MatiasNielsen** [comment]
my project.clj looks like this:

`(defproject hello-world "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.0"][lein-auto "0.1.3"]
            [jonase/eastwood "0.3.5"]
            [lein-kibit "0.1.7"]
            [lein-ancient "0.6.15"]
            [lein-cloverage "1.1.1"]
            [lein-nvd "1.0.0"]]
  :plugins [[lein-auto "0.1.3"]
            [jonase/eastwood "0.3.5"]
            [lein-kibit "0.1.7"]
            [lein-ancient "0.6.15"]
            [lein-cloverage "1.1.1"]
            [lein-nvd "1.0.0"]
  ]
  :profiles {:dev {:source-paths ["dev"]
                   :plugins [[jonase/eastwood "0.3.5"]
                   [lein-kibit "0.1.7"]
                   [lein-ancient "0.6.15"]
                   [lein-cloverage "1.1.1"]
                   [lein-nvd "1.0.0"]]
                   :eastwood {:add-linters [:unused-fn-args
                                            :unused-locals
                                            :unused-namespaces
                                            :unused-private-vars]
                              :exclude-namespaces [transmogrif.cli.legacy transmogrif.pipeline transmogrif.pipeline-test]}}}
  :repl-options {:init-ns hello-world.core})
`

Funny thing is, when i run lein kibit from commandline, inside the folder where project.clj is, it works. And if i do lein help it also shows up as a task.. when im just in the root folder of the project(not in the same folder of the project.clj) it says its not a task...

I am currently trying to make it work in a docker through jenkins.

1. Build image that installs lein and sonar scanner
2. Run image that runs sonar scanner on a directory
3. Lein is not a task :(

**Comment by MatiasNielsen** [comment]
Currently using this 

docker run -v $(pwd):/root/src/ sonar-test  -X \
                -Dsonar.host.url=http://someserver:9000 \
                -Dsonar.jdbc.url=jdbc:h2:tcp://sonarqube/sonar \
                -Dsonar.projectKey=clojurekeyhelloworld \
                -Dsonar.projectName="My test Name" \
                -Dsonar.projectVersion=1 \
                -Dsonar.projectBaseDir=/root/src/hello-world \
                -Dsonar.sources=project.clj \
                -Dsonar.clojure.lein-nvd.json-output-location=./target/nvd/dependency-check-report.json \
                -Dsonar.clojure.cloverage.json-output-location=./target/coverage/codecov.json'


the project.clj is inside the hello-world folder in the projectbasedir...

**Comment by fsantiag** [comment]
It seems your jenkins docker agent is misconfigured or something. If you try to run the sonar-scanner locally, does it publish data to your sonar server?
If the answer is yes, that means it is the agent configuration. Try to see from which directory lein is being invoked inside the container.

**Comment by Rulqu** [comment]
Any news when this will be fixed?

**Comment by fsantiag** [comment]
I've been super busy in the past few months but I will try to spend some time to fix this in the upcoming weeks. Feel free to open a PR if you already have something working. :)

**Comment by fsantiag** [comment]
I believe this issue is fixed with this commit 5431aaf43ef4c2ab4b8c68b91c3848483f00893c.
I would say it is a temporary solution since the LOC provided is not 100% accurate, however it does the job of not generating empty reports in the Sonar UI.
