### ISSUE TITLE
Options for plugins

### ISSUE THREAD

**Issue by mishadoff** [fsantiag/sonar-clojure#26]
Is there a way to pass specific properties for clojure plugins when executed by sonar 
(e.g eastwood need `{:continue-on-exception true}` to tolerate exception during linting.

Also would be good to see in debug level what commands is executed by sonar, because now behaviour is 

```
INFO: Clojure project detected
INFO: Running Eastwood
WARN: Eastwood resulted in empty output
INFO: Saving issues
```

no hint what happened, even with -X option for sonar-scanner.

**Comment by fsantiag** [comment]
At the moment we don't have this feature, but it definitely a nice feature to have. Not only for eastwood but for the other sensors as well.

**Comment by naiquevin** [comment]
We are interested in this feature too. Don't have a solution in mind that would be generic for all sensors but for eastwood specifically, may be we can have `EastwoodSensor.EASTWOOD_COMMAND` configurable from outside (eg. as a property). What do you think?

**Comment by mishadoff** [comment]
@naiquevin Yeah, it's done in PR https://github.com/fsantiag/sonar-clojure/pull/27 but still not merged. If that blocks you can try to build a jar from branch where it's fixed.

**Comment by fsantiag** [comment]
Since we have other people depending on this feature, I decided to merge @mishadoff PR and we can think about a broader solution later.

**Comment by fsantiag** [comment]
It is available on the latest release: https://github.com/fsantiag/sonar-clojure/releases/tag/v1.6.0
