### ISSUE TITLE
sonar-scanner should show Cloverage run log in debug mode

### ISSUE THREAD

**Issue by 123BLiN** [fsantiag/sonar-clojure#29]
**Describe the solution you'd like**
It will be very useful to see Cloverage run log in debug mode

**Describe alternatives you've considered**
Add recommendation to use `lein cloverage --codecov` in Readme troubleshooting section (for non clojure developers like me)

**Additional context**
Spent insane amount of time to try to understand why I don't have cloverage report, even in debug mode it looks like so:
```
INFO: Running Cloverage

WARN: Cloverage report does not exists. Have you added added target/coverage/codecov.json to sonar.clojure.cloverage.json-output-location?

INFO: Sensor SonarClojureCloverage [clojure] (done) | time=53701ms
```
That is pretty misleading 
CC @mishadoff

**Comment by fsantiag** [comment]
Hi @123BLiN! Thank you for your contribution.

The suggestion you gave was pretty nice and I already implemented. It works for all sensors now, not only for Cloverage.

Cheers!
