### ISSUE TITLE
Running lein eastwood times out after 5 minutes

### ISSUE THREAD

**Issue by neha-helpshift** [fsantiag/sonar-clojure#30]
I can see that the timeout has been set to 5 minutes for the command to run. But I have a project on which eastwood takes more than 20 minutes to run. Can we have the timeout customisable? or are there any other solutions to this?

**Comment by fsantiag** [comment]
Hi @neha-helpshift, unfortunately we don't have a way to set the timeout but we could explore how to add that to sonar-clojure. If you have thoughts, feel free to let me know. For now I will mark this issue as a feature request while we think about something.

**Comment by fsantiag** [comment]
Hi again @neha-helpshift, I am externalizing a property to control the default command executor timeout. I will keep you posted.
