### ISSUE TITLE
Disabling a sensor doesn't work

### ISSUE THREAD

**Issue by Rulqu** [fsantiag/sonar-clojure#37]
**Describe the bug**
I tried many ways to disable the ancient plugin from running and it doesn't seem to work.

**How to reproduce**
Add `sonar.clojure.ancient.disabled=true` or `sonar.clojure.lein-ancient.disabled=true` to sonar-project.properties` and run the sonar-clojure

I tried that "lein-ancient" because I wanted to be sure if the main README.md is not typoed.

**Expected behavior**
Lein-ancient not running

**Logs from Jenkins**
```
INFO: Running Lein Ancient
.
.
.
```

**Additional context**
 - SonarQube Version 7.9.1
 - SonarQube Scanner 4.2.0.1873
 - Java 1.8.0_242

**Comment by Rulqu** [comment]
I tried with
```
sonar.clojure.ancient.disabled=true
sonar.clojure.cloverage.disabled=true
sonar.clojure.eastwood.disabled=true
sonar.clojure.nvd.disabled=true
sonar.clojure.kibit.disabled=true
```
and only Eastwood and Kibit were disabled.

**Comment by fsantiag** [comment]
Hi @Rulqu, thanks for your time reporting this issue. I just ran the scanner and it seems to be working as expected for me.
The scanner output has the following:
```
INFO: Sensor Eastwood [clojure]
INFO: Eastwood disabled
INFO: Sensor Eastwood [clojure] (done) | time=0ms
INFO: Sensor Kibit [clojure]
INFO: Kibit disabled
INFO: Sensor Kibit [clojure] (done) | time=0ms
INFO: Sensor Ancient [clojure]
INFO: Ancient disabled
INFO: Sensor Ancient [clojure] (done) | time=1ms
INFO: Sensor Cloverage [clojure]
INFO: Cloverage disabled
INFO: Sensor Cloverage [clojure] (done) | time=0ms
INFO: Sensor NVD [clojure]
INFO: NVD disabled
INFO: Sensor NVD [clojure] (done) | time=0ms
```

I disabled all of them as you did and used the same version for sonarqube and the sonar-scanner.

Where did you place the sonar-project.properties? Have you set all the configs? It seems the scanner is ignoring the file or something.
