### ISSUE TITLE
Deps edn integration

### ISSUE THREAD

**Issue by yhrabovskyinomi** [fsantiag/sonar-clojure#43]
**Describe the solution you'd like**
I want to integrate same plugin but not with 'lein' but this deps edn cli (simple clj) 

I am wondering if someone already had experience configuring this with clojure cli?

And any luck this can be added in future or you will proceed working only on lein version?

**Comment by fsantiag** [comment]
Hi @yhrabovskyinomi,

I am not familiar with the tool you are referring to. Could you share a link about it?
Depending on the tool, it might be possible to integrate it to the plugin.

**Comment by yhrabovskyinomi** [comment]
Hey @fsantiag , i mean this default clj cli https://clojure.org/guides/deps_and_cli based on deps.edn

**Comment by fsantiag** [comment]
Hi @yhrabovskyinomi, sorry for the late reply!

Unfortunately, implementing something like that would take a lot of effort and I am not sure how much benefit would bring to the rest of the community. Having said that, I am closing this issue.
In any case, if you have to have implemented something like that on your fork, feel free to open a PR. I am happy to discuss these changes over a PR.

Cheers!

**Comment by alza-bitz** [comment]
Hi @fsantiag looking at the growth of deps.edn (and the decline of project.clj) as reported in the State of Clojure 2022 results, would you reconsider adding deps.edn support? Thanks 🙏

https://clojure.org/news/2022/06/02/state-of-clojure-2022#_working_with_clojure
